### ISSUE TITLE
Gravity Forms doesn't trigger success event when redirecting.

### ISSUE THREAD

**Issue by danieliser** [PopupMaker/Popup-Maker#685] opened 2019-09-18 22:22 UTC
This leads to support tickets regularly. We either need to craft a foolproof solution to work after the redirect, or put a better notice that this could happen and they should manually redirect using JavaScript in the confirmation text

     <script>setTimeout(function () { window.location = "redirect url here"; }, 300);</script>

**Comment by fpcorso** [comment] 2020-10-21 16:17
Duplicate of #644

**Closed by fpcorso** 2020-10-21 16:17 UTC
