### ISSUE TITLE
1.3 breaks landing page, 1.2 works fine

### ISSUE THREAD

**Issue by mholen** [PopupMaker/Popup-Maker#123] opened 2015-07-31 00:37 UTC
I'm trying to use 1.3 to pass the post title through Popup Maker so I can see where the conversion comes from, but when I deactivate 1.2 and activate 1.3, it breaks my landing page. I have no idea why, but I recreated the landing page on another instance of wordpress, so you can see both working and broken:

Working (1.2): http://www.realendeavors.com/owner-financing/
Broken (1.3): http://www.selltomiles.com/realendeavors/owner-financing/

Please let me know if you know something I don't!

**Comment by danieliser** [comment] 2015-07-31 00:58
Looks like your text-3 text widget has too many or not enough close </divs>. My guess is not enough since the popups are ending up inside of it in the rendered version.

**Comment by danieliser** [comment] 2015-07-31 01:01
This isn't apparent in v1.2 because it forced all popups to be moved to the footer using JS. in v1.3 we made it so that they can remain in their original location. But I checked and both are missing a closing /div in that widget in your footer.

**Comment by mholen** [comment] 2015-07-31 01:11
Ah you are correct, I was missing a /div. However, I added it to both sites and the page still isn't loading with 1.3

**Comment by danieliser** [comment] 2015-07-31 01:18
@mholen - Hmm looks like your content div is empty on the test site. Can you check your php error logs. We don't do any filtering on the_content so I can't see why that would have an effect. Also no JS errors so I am at a loss as to what would cause it other than a PHP error.

**Comment by mholen** [comment] 2015-07-31 02:08
Can I get your email so I can send you my error log? I'm not sure what I'm looking at...

**Comment by danieliser** [comment] 2015-07-31 02:09
@mholen - Sure danieliser at wizardinternetsolutions.com

**Comment by mholen** [comment] 2015-07-31 02:33
Thanks, I've sent it there

**Comment by danieliser** [comment] 2015-07-31 02:49
@mholen - Hmm nothing there related to popup maker at all. The only errors are with widget logic.

**Comment by mholen** [comment] 2015-07-31 03:33
Strange. I wonder what's unique about 1.3 that's causing the issue.

**Comment by danieliser** [comment] 2015-07-31 05:39
@mholen - I have ~30 testers on various setups and haven't seen this issue so I'm wondering if it is theme or plugin related. Any chance you can start testing plugin compatibility? Disable a couple plugins at a time until it starts working? If that doesn't work then its in the theme compatibility.

Can you post the contents of the debug info (Popup Maker -> Tools)?

**Comment by mholen** [comment] 2015-07-31 14:12
I just deactivated every plugin on the test site except Popup Maker 1.3 and it's still returning the blank page. I have left the plugins disabled, so feel free to have a look if you like. I guess this means it's a theme compatibility issue?

Also I just emailed you my Popup Maker debug info.

**Comment by danieliser** [comment] 2015-07-31 18:21
Hey Mholen,Looking like it but I'd be interested to find out why. Seems like the issue has to do with the_content since that's what isn't being rendered. Everything else is appearing like it should in the HTML. Head, footer etc.Ill have a look at debug and see if anything pops out at me.---- On Fri, 31 Jul 2015 10:12:16 -0400  mholen<notifications@github.com> wrote ----I just deactivated every plugin on the test site except Popup Maker 1.3 and it's still returning the blank page. I have left the plugins disabled, so feel free to have a look if you like. I guess this means it's a theme compatibility issue?Also I just emailed you my Popup Maker debug info.—Reply to this email directly or view it on GitHub.

**Comment by danieliser** [comment] 2015-07-31 19:41
@mholen - It may be worth asking the theme developer what they think could be causing it. Just did a search on our entire v1.3 code base and we are not doing anything with the content of the typical page except rendering our own shortcodes. Are you using [popup] or [popup_trigger] anywhere in your page? If so maybe try removing those and see if that is the cause.

Next step if theme has no answer is to do a line by line commenting of our scripts to find which file is causing the issue, then start commenting out sections of that file until it goes away. From there I can at least try to determine why that section is breaking it.


But in that case I either need ftp access to your test site or a backup of it that I can use to work from on my own test server.


Gladly willing to get this resolved but definitely need more than I have to go on.

---- On Fri, 31 Jul 2015 10:12:16 -0400 mholen&lt;notifications@github.com&gt; wrote ---- 

I just deactivated every plugin on the test site except Popup Maker 1.3 and it's still returning the blank page. I have left the plugins disabled, so feel free to have a look if you like. I guess this means it's a theme compatibility issue?
 Also I just emailed you my Popup Maker debug info.

**Comment by mholen** [comment] 2015-08-08 08:04
I haven't gotten a response from the theme support. I'm emailing you credentials for my test site. Thank you for looking into this.

**Comment by danieliser** [comment] 2015-08-08 08:05
@mholen - Will look into this tomorrow, its already 4am here.

**Comment by mholen** [comment] 2015-08-08 08:07
Ha yeah it's 4am here too. No rush at all.

**Closed** 2016-09-30 05:04 UTC
