### ISSUE TITLE
Internet Explorer 11 does not support JS Promises

### ISSUE THREAD

**Issue by danieliser** [PopupMaker/Popup-Maker#870] opened 2020-08-12 21:18 UTC
## Describe the bug
Popups no longer function reliably on IE11.

## Site information
Popup Maker version: 1.11.0

WordPress version: 5.5

PHP version: 7.4

## Expected behavior
Promise support needs a backward compatible polyfill.

## Current behavior
JavaScript errors when init calls for Promise.all()

## Steps to reproduce
1. Run site on IE11

## Errors
Promise function doesn't exist.

## Additional context
This is probably a good starting point: https://www.npmjs.com/package/promise-polyfill

**Comment by fpcorso** [comment] 2020-08-13 15:00
@danieliser This is a duplicate of #836, right? Or are these two separate bugs?

**Comment by fpcorso** [comment] 2020-08-14 18:01
@danieliser I noticed in the support forums we have been recommending people to use BlueBird JS but you mentioned the promise-polyfill here. Do you have a preference for which library we should use?

**Comment by danieliser** [comment] 2020-08-14 18:23
@fpcorso This does appear to be a duplicate of #836. We can merge/close one.

I don't know where the Bluebird JS solution came from honestly. This is the most popular npm package I can find.

But if that works for now I'm good with using it as a stop gap if its easier for you to roll into existing build tools that way.

**Comment by fpcorso** [comment] 2020-08-14 19:03
@danieliser I just looked through BlueBird JS and it seems to be a bit more extensive and feature-full than the polyfill you found. Probably better for us to stick to the polyfill so we don't introduce too much unneeded code.

**Comment by fpcorso** [comment] 2020-08-14 19:41
Added the polyfill from npm to the `site/vendor` folder. Gulp correctly used that during the build process.

**Closed by fpcorso** 2020-08-14 19:41 UTC
Labels: type-bug
