### ISSUE TITLE
IE11 Doesn't support JS Promise generating errors

### ISSUE THREAD

**Issue by danieliser** [PopupMaker/Popup-Maker#836] opened 2020-07-07 08:29 UTC
https://wordpress.org/support/topic/bug-report-120/

https://stackoverflow.com/questions/36016327/how-to-make-promises-work-in-ie11

**Comment by fpcorso** [comment] 2020-08-14 19:01
Duplicate of #870

**Closed by fpcorso** 2020-08-14 19:01 UTC
