### ISSUE TITLE
Automagically enqueue popups when detected during page load.

### ISSUE THREAD

**Issue by danieliser** [PopupMaker/Popup-Maker#543] opened 2018-03-22 23:08 UTC
- [x] When rendering nav menu items that link to a specific popup.
- [x] When a nav menu item has a class of popmake- or pum-
- [x] When the [popup_trigger] shortcode is used.
- [x] When the_content contains classes or a shortcode for a particular popup

**Comment by fpcorso** [comment] 2020-07-10 17:55
@danieliser Is this a duplicate of #96 or would #96 be one more checkbox for this issue?

**Comment by danieliser** [comment] 2020-07-14 19:30
@fpcorso I think #96 would be a checkbox here.

**Comment by danieliser** [comment] 2020-07-14 19:30
Maybe close that one and move its notes here as a subtask.

**Comment by fpcorso** [comment] 2020-12-11 21:28
@danieliser Knowing we are removing the old form integration system, do we still need that step of checking for the thank you option? Additionally, should we check for forms on a page that one of the popups has a form submission trigger for?

**Comment by danieliser** [comment] 2020-12-14 19:50
@fpcorso Good point, but removing and deprecating are 2 different things. To fully remove it we'd have to do migration routines for all of the orignal form integrations, pulling settings from each form and mapping it over all their popups (maybe).

So we should likely contend that it will still be functioning for some time and would need to catch those as well.

**Comment by fpcorso** [comment] 2020-12-21 17:13
@danieliser Okay, that sounds good for my first question. Can you answer my second question?

**Comment by fpcorso** [comment] 2020-12-21 21:41
@danieliser Also, in addition to my previous question: Was reviewing the code and it seems like the PUM_Site_* classes will handle everything as long as I run `PUM_Site_Popups::preload_popup( $popup );` when a popup is needed, right?

So, if we have a filter for the content that scans for a PM class, we would just need to call that for the needed popup, right? Or am I missing a piece?

**Comment by danieliser** [comment] 2020-12-22 00:30
@fpcorso first question, maybe. We could probably do that as an upgrade later as well.

And yes `preload_popup` should do the trick, it was the original intent of that method I believe.

**Comment by fpcorso** [comment] 2020-12-22 14:15
@danieliser For within `the_content` filter, should we only enqueue when on the individual post's page or should we also load our popup if the content is loaded on an archives page or elsewhere?

I.e., should I add a conditional such as `is_singular() && in_the_loop() && is_main_query()`?

**Comment by fpcorso** [comment] 2020-12-22 15:11
@danieliser In addition to previous questions: What about enabled/disabled? Should we only preload when the popup is enabled? I can see it both ways but I think we should go with only loading if enabled.

**Comment by danieliser** [comment] 2020-12-22 17:57
@fpcorso 

> should we only enqueue when on the individual post's page or should we also load our popup if the content is loaded on an archives page or elsewhere?

Ehh, torn, the latter is more feature complete, but it becomes difficult to properly scan all the popups needed early enough that they can include their needed assets. 

To clarify, if a popup contains a form for example, and that form needs assets enqueued before wp_head, and we don't scan its shortcode in a popup until that popup gets enqueud in the loop somewhere it might fail to function properly.

> enabled/disabled

I think this one is more simple, we gave them an explicit method to disable a popup, we should 100% respect that. So no I wouldn't scan for a disabled popup.

**Closed** 2020-12-30 14:44 UTC
Labels: type-improvement
