### ISSUE TITLE
Error when no sound option set

### ISSUE THREAD

**Issue by danieliser** [PopupMaker/Popup-Maker#771] opened 2020-03-27 05:28 UTC
This error occurs when a popup has no sound setting passed in. This will show up in mass as nobodies current popups will have this setting in their popup_settings arrays.

![image](https://user-images.githubusercontent.com/847818/77724421-4ed65380-6fc9-11ea-9a97-a27e77830567.png)

We need to check that the variable is not undefined before firing this up.

Change it to something like this and it didn't error any longer.

                if ( settings.open_sound && 'none' !== settings.open_sound ) {

**Comment by danieliser** [comment] 2020-03-27 05:42
@fpcorso side note, site scripts are not yet run through webpack, so you can't use ES6 currently. We need to replace the fat arrow functions with normal ones for those lines as well locally.

To move site scripts to webpack requires some time investment to redo all the imports properly.

**Comment by fpcorso** [comment] 2020-03-28 01:08
@danieliser, Hmmm... I recall running into this exact error and identifying the cause and I could have sworn I solved this. Maybe it's in a commit locally somewhere. Regardless, will get this fixed.


As for the ES6, for some reason, I was thinking we couldn't use ES6 on the PM site but could in the plugin due to the build system. No worries. I'll have to update code for both this and my other 1.10

**Comment by danieliser** [comment] 2020-03-28 01:27
@fpcorso No worries. We are moving that direction, 30% of the plugin uses ES6 bundling already, migrating the rest over a few versions, as we can.

**Comment by fpcorso** [comment] 2020-03-28 01:43
Sound issue is fixed in the recent commit.

**Closed by fpcorso** 2020-03-28 01:43 UTC
Labels: component-front-end, priority-high, type-bug

**Comment by danieliser** [comment] 2020-03-28 01:50
Perfect

**Comment by danieliser** [comment] 2020-03-28 02:01
I never committed it but here is the fixes for ES6 in pum.js

```
               // If our opening sound setting is not set to None...
                if ( settings.open_sound && 'none' !== settings.open_sound ) {
					// ... then set up our audio. Once loaded, add to popup data.
					var audio = 'custom' !== settings.open_sound ? new Audio( pum_vars.pm_dir_url + '/assets/sounds/' + settings.open_sound ) : new Audio( settings.custom_sound );
					audio.addEventListener('canplaythrough', function() {
						$popup.data('popAudio', audio);
					});
					audio.addEventListener('error', function() {
						console.warn( 'Error occurred when trying to load Popup opening sound.' );
					});
```

```
			// If the audio hasn't loaded yet, it wouldn't have been added to the popup.
            if ( 'undefined' !== typeof $popup.data('popAudio') ) {
				$popup.data('popAudio').play()
					.catch(function (reason) {
						console.warn("Sound was not able to play when popup opened. Reason: " + reason + ".");
					});
			}
```
