### ISSUE TITLE
Disable plugin on a specific page

### ISSUE THREAD

**Issue by Touma08** [PopupMaker/Popup-Maker#601] opened 2018-10-18 13:25 UTC
Hello. I'm having an issue on regards the plugin. It's complicating on gravity forms. So my plan is just disable or unhook the plugin on a specific page. and just re activate it once the user is out of the page

function disable_plugins(){
if( is_page(2690) ) {
    deactivate_plugins( '/popup-maker/popup-maker.php');
} else {
    //reactivate the plugin
}
} add_filter('option_active_plugins', 'disable_plugins');

**Comment by rgadon107** [comment] 2018-10-18 16:20
@Touma08 There's an even simpler solution compared to what you describe in your earlier post. Use _targeting conditions_ provided within Popup Maker.  We describe their use clearly in great detail in our documentation. 

https://docs.wppopupmaker.com/article/351-popup-settings-box-targeting-option-settings

Since you did not provide a URL for us to inspect, we have no knowledge as to how you are using GF with PUM. For example, if you add a GF form shortcode into a popup, _and_ add the same shortcode into a content area (e.g. post, page, widget area), the form in the popup will not process. 

https://docs.wppopupmaker.com/article/368-why-is-a-form-not-working-in-my-popup

Best to step back first and consider other possibilities as to what might be the root cause of your problem before you implement a custom solution.

**Comment by danieliser** [comment] 2018-10-19 08:21
@Touma08 Wrong place for this anyways. Closing.

**Closed by danieliser** 2018-10-19 08:21 UTC
