### ISSUE TITLE
Add notices that cache may need flushing, automate cache flushing when able.

### ISSUE THREAD

**Issue by danieliser** [PopupMaker/Popup-Maker#547] opened 2018-03-29 22:27 UTC
Caching has become a major issue during update cycles for whatever reason. Page caching has always been an issue, but now more so. Since we can't integrate with every caching plugin best to notify users that clearing cache after saving popups or PM - > settings may be necessary at a minimum.

**Comment by yumyo** [comment] 2018-04-09 16:36
Same here, 'causing a broken cookie handling behaviour on our setup

**Comment by fpcorso** [comment] 2020-06-03 15:21
@danieliser What are your current thoughts on this? Do you think we should still add a notice?

If so, would it be a message when someone updates a popup or theme telling admin to flush their cache or would there be a different solution that you are thinking of?

**Comment by danieliser** [comment] 2020-06-03 21:32
@fpcorso - Maybe we should aim to just flush caches programmatically. We have the means, we can find other plugins that do it already and just copy what they do.

**Comment by fpcorso** [comment] 2020-06-04 15:31
@danieliser Doesn't each caching plugin manage that differently? Wouldn't flushing caches programmatically require us to utilize code to manage cache for each caching plugin?

**Comment by danieliser** [comment] 2020-06-04 19:42
@fpcorso Correct, but that is why I suggested using another plugin that already offers that via the GPL to shortcut those concerns.

There are a few plugins that do that, but Beaver Builder has it built in somewhere, a list of providers and callbacks for each is all it takes.

**Comment by fpcorso** [comment] 2020-09-30 13:53
Duplicate of #582

**Closed by fpcorso** 2020-09-30 13:53 UTC
